Retry 3 times

diff --git a/.github/workflows/gasprice.yml b/.github/workflows/gasprice.yml
--- a/.github/workflows/gasprice.yml
+++ b/.github/workflows/gasprice.yml
@@ -25,7 +25,11 @@ jobs:
 
       - name: Retrieve gas price data
         run: |
-          python gasprice.py
+          # Retry 3 times
+          (echo "===== Attempt: 1 ====" && python gasprice.py) || \
+          (echo "===== Attempt: 2 ====" && python gasprice.py) || \
+          (echo "===== Attempt: 3 ====" && python gasprice.py) || \
+          (echo "==== Crawler Failed ====" && exit 1)
 
       - name: Commit files
         run: |
